### ISSUE TITLE
Number.toUnsigned()

### ISSUE THREAD

**Issue by radare** [wargio/r2dec-js#15]
```
[0x1000011e0]> . inr2.js
TypeError: obj.offset.toUnsigned is not a function
    at new Instruction (/Users/pancake/prg/r2dec-js/decompile/instruction.js:43:34)
    at /Users/pancake/prg/r2dec-js/decompile/metadata.js:40:20
    at Array.map (native)
    at new Metadata (/Users/pancake/prg/r2dec-js/decompile/metadata.js:39:12)
    at r2dec.work (/Users/pancake/prg/r2dec-js/r2dec.js:45:24)
    at asyncMain (/Users/pancake/prg/r2dec-js/inr2.js:60:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by wargio** [comment]
ehm, binary?

**Comment by radare** [comment]
its a number
