### ISSUE TITLE
TypeError: Cannot read property 'casts' of undefined on the main of /bin/ls

### ISSUE THREAD

**Issue by ampotos** [wargio/r2dec-js#33]
Hi,

I tried r2dec for the first time today and I got this error:
```
TypeError: Cannot read property 'casts' of undefined
    at _apply_bits (/home/ampotos/.config/radare2/r2pm/git/r2dec-js/libdec/arch/base.js:132:21)
    at _bits_argument.toString (/home/ampotos/.config/radare2/r2pm/git/r2dec-js/libdec/arch/base.js:148:20)
    at xor (/home/ampotos/.config/radare2/r2pm/git/r2dec-js/libdec/arch/base.js:343:30)
    at _common_math (/home/ampotos/.config/radare2/r2pm/git/r2dec-js/libdec/arch/x86.js:72:16)
    at xor (/home/ampotos/.config/radare2/r2pm/git/r2dec-js/libdec/arch/x86.js:294:24)
    at _analyze_instructions (/home/ampotos/.config/radare2/r2pm/git/r2dec-js/libdec/core/Analyzer.js:62:32)
    at Analyzer.analyze (/home/ampotos/.config/radare2/r2pm/git/r2dec-js/libdec/core/Analyzer.js:96:13)
    at asyncMain (/home/ampotos/.config/radare2/r2pm/git/r2dec-js/r2dec.js:129:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
undefined
```

The output of  #!pipe r2dec --issue: 
https://gist.github.com/ampotos/bb44e60d2255ed463690c27db79ec5d8

I can try to help but I'm not use to JS at all

**Comment by ampotos** [comment]
It works well on a hello world function but I it the same bug with more complicated ones.

**Comment by wargio** [comment]
fixed
